language: generic

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
compiler:
  
CXX = g++-5
CXXFLAGS
  
script: $(CXX) *.cpp -Wall -Wextra --std=c++14

notifications:
  email: false
